force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>hyderabad</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
            <value>
                <fullName>mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/hiringmanagerhelper.cls
@restresource(URLMapping='/hiringmanagerservice/*')
Global class hiringmanagerhelper 
{
    @httpPost()
   global static Hiring_Manager__c createHRrecords(string hrname,string hrlocation,string hrphone,string hremail)
   {
       Hiring_Manager__c hr=new Hiring_Manager__c();
       hr.Name=hrname;
       hr.Location__c=hrlocation;
       hr.Contact_number__c=hrphone;
       hr.Email_ID__c=hremail;
       
       
       insert hr;
       return hr;
   }
}