force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>hyderabad</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
            <value>
                <fullName>mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/databaseHelper.cls
public class databaseHelper
{
    public static void GetAccountsbyindustry(string accountindustry)
    {
        if(accountindustry !=null && accountindustry != '')
        {
            for(account acc : [select id,name,industry,annualrevenue from account
                             								where industry =: accountindustry])
            {
                system.debug('account record is...'+ acc);
            }
        }
    }

    public static void Getcasebystatus(string casestatus)
    {
        if (casestatus !=null && casestatus !='')
        {
            for (case cs :[select id,status,priority,origin,type,reason,subject,casenumber from case
                            													where status=:casestatus])
            {
                system.debug('case record is....'+cs);
            }
        }
    }
 public static void GetAllHRrecords()
 {
     for(Hiring_Manager__c hr : [select id,name,email_id__c,contact_number__c,location__c from Hiring_Manager__c])
     {
         system.debug('HR name is....:'+ hr.Name);
         system.debug('HR id is....'+hr.Id);
         system.debug('HR location is...'+hr.Location__c);
         system.debug('HR contact number is....'+hr.Contact_number__c);
     }
 }
}