force-app/main/default/objects/position__c/fields/Annualrevenue__c.field-meta.xml
<CustomField>
    <fullName>Annualrevenue__c</fullName>
    <label>Annualrevenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/position__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <label>location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>bangalore</fullName>
            </value>
            <value>
                <fullName>chenni</fullName>
            </value>
            <value>
                <fullName>hyderabad</fullName>
            </value>
            <value>
                <fullName>mumbai</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/position__c/fields/position__c.field-meta.xml
<CustomField>
    <fullName>position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>customer</label>
    <referenceTo>customer__c</referenceTo>
    <relationshipLabel>positions</relationshipLabel>
    <relationshipName>positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/position__c/fields/position_status__c.field-meta.xml
<CustomField>
    <fullName>position_status__c</fullName>
    <label>position status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>closed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>new</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/positionhelper.cls
@restresource(urlmapping='/chandusai/*')
global class positionhelper 
{
    @httpget()
global static list<position__c> getpositions()
{
    
    map<string,string> mapsetlocation = RestContext.request.params;
    list<position__c> lstposition =[select id,position_status__c,location__c,Annualrevenue__c from position__c where 
                                    location__c =: mapsetlocation.get('location__c')];
    return lstposition;

}
}