force-app/main/default/objects/candidate__c/candidate__c.object-meta.xml
<CustomObject>
    <description>To store the persons record informations</description>
    <label>candidate</label>
    <nameField>
        <label>candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/candidate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>mumbai</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
            <value>
                <fullName>warangal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/candidate__c/fields/Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period__c</fullName>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 days</fullName>
            </value>
            <value>
                <fullName>20 days</fullName>
            </value>
            <value>
                <fullName>1 months</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/position__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <label>location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>bangalore</fullName>
            </value>
            <value>
                <fullName>chenni</fullName>
            </value>
            <value>
                <fullName>hyderabad</fullName>
            </value>
            <value>
                <fullName>mumbai</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/position__c/fields/position__c.field-meta.xml
<CustomField>
    <fullName>position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>customer</label>
    <referenceTo>customer__c</referenceTo>
    <relationshipLabel>positions</relationshipLabel>
    <relationshipName>positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/databasehelper2.cls
public class databasehelper2 
{
    public static void GetcontactByAccountIndustry(string industryname)
    {
        if(industryname !=null && industryname !='')
       {
          map<id,Account> mapAccounts =new map<id,Account>([select id,name,industry
                                                                 from account
                                                                   where industry =:industryname]);
           if(! mapAccounts.isempty())
           {
               list<contact> lstcontacts =[select id,firstname,lastname,email,phone,fax,accountid 
                                                    from contact
                                                     where accountid IN :mapaccounts.keyset()];
               for(contact con : lstcontacts)
               {
                   system.debug('contact record is...:'+con);
               }
           }
       }
    }
    public static void GetcandidateByEndingName(string Endingchar)
    {
        if(Endingchar != null && Endingchar !='')
        {
            Endingchar +='%';
            list<candidate__c> lstcandidate =[select id,name,location__c,notice_period__c
                                                              from candidate__c
                                             						where name like :Endingchar ];
            system.debug('collection size is...:'+lstcandidate.size());
            for(candidate__c con : lstcandidate)
            {
                system.debug('candidate record is...'+ con);
            }
        }
    }
    public static void GetAccountsByStarting(String startingChar)
    {
        if(startingchar != null && startingchar !='')
        {
            startingchar +='%';
            list<account> lstaccounts =[select id,name,industry,rating,annualrevenue 
                                                       from Account
                                                  where name like: startingchar ];
            system.debug('collection size is.........:'+lstaccounts.size());
            for(account acc : lstaccounts)
            {
                system.debug('accounts records are....'+acc);
            }
        }
    }
    public static void GetAllposition(string positionlocation)
    {
     if(positionlocation !=null && positionlocation !='')
     {
         for(position__c pos :[select id,name,email__c,location__c from position__c
                                                          where
                                                              location__c =:positionlocation])
         {
             system.debug('position record is...'+ pos);
         }
     }
    }
}